name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Python syntax
      run: |
        python -m py_compile guardian.py web.py
        echo "✅ Python syntax check passed"
    
    - name: Test Docker build
      run: |
        docker build -t guardian- .
        echo "✅ Docker build test passed"
    
    - name: Test Docker run
      run: |
        docker run --rm -d --name guardian-test -p 8080:8080 guardian-
        sleep 5
        curl -f http://localhost:8080 || exit 1
        docker stop guardian-test
        echo "✅ Docker run test passed"

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
